# Используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# Используем режим обычного пользователя для сборки проекта.
sudo: false

# После выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo.
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту valeriyfinans@gmail.com (изменить на свою) если сборка упала.
notifications:
  email:
    recipients:
      - valeriyfinans@gmail.com
    on_success: never # default: change
    on_failure: always # default: always